name: Build Stdlibs

on:
  workflow_dispatch:
      inputs:
        enable_tests:
          type: choice
          description: 'Enable Tests'
          deprecationMessage: 'true or false'
          required: true
          options:
            - 'true'
            - 'false'
          default: 'true'

jobs:
  build-pipeline:
    name: Build Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python Packages
        run: |
          pip install requests
          pip install retry
          pip install PyGithub

      - name: Build Modules
        run: |
          python scripts/build_stdlibs.py ${{ github.event.inputs.enable_tests }}
        env:
          BALLERINA_BOT_USERNAME: ${{ secrets.BALLERINA_BOT_USERNAME }}
          BALLERINA_BOT_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
