name: Build Linux ARM Installer

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Linux ARM Installer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Clone ballerina-distribution repository
        run: git clone https://github.com/ballerina-platform/ballerina-distribution.git
      - name: Download linux zip
        run: |
          wget https://drive.google.com/file/d/1x2yi4ZhxxcWrJ7e9ggeFzcyARkJtdb08/view?usp=sharing
      - name: Build deb installer
        working-directory: ballerina-distribution/installers/linux-deb
        run: |
          ./build-ballerina-linux-deb-x64.sh -v 2201.10.2-swan-lake -p ./../../../resources
      - name: Archive Linux deb
        uses: actions/upload-artifact@v4
        with:
          name: Linux Installer deb
          path: ballerina-distribution/installers/linux-deb/target/ballerina-*-linux-x64.deb
          
        

