name: Build BBEs

on:
  workflow_dispatch:

jobs:
  initialize-matrix:
    name: Initialize Strategy Matrix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Strategy Matrix
        id: set-matrix
        run: |
          SAMPLES="`jq -r '.[]' examples/index.json`"
          echo ${SAMPLES[0]}

#          echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json --names)"
#    outputs:
#      matrix: ${{ steps.set-matrix.outputs.matrix }}
#
#  build-bbe:
#    needs: initialize-matrix
#    name: Build BBE
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        package: ${{ fromJson(needs.initialize-matrix.outputs.matrix) }}
#
#    steps:
#      - name: Ballerina Build
#        uses: ballerina-platform/ballerina-action@master
#        with:
#          args:
#            build
