name: Build BBEs

on:
  workflow_dispatch:

jobs:
  initialize-matrix:
    name: Initialize Strategy Matrix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Strategy Matrix
        id: set-matrix
        run: |
          arr=( $(jq -r '.[] | {title: .title}' examples/index.json) )
          echo ${arr[0]}
          for testGroup in "`jq -r '.[] | {title: .title}' examples/index.json`"; do echo $testGroup; done
#          for testGroup in "`jq -r '. | {title: .title, category: .category}' examples/index.json`"; do echo $testGroup; done

#          echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json --names)"
#    outputs:
#      matrix: ${{ steps.set-matrix.outputs.matrix }}
#
#  build-bbe:
#    needs: initialize-matrix
#    name: Build BBE
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        package: ${{ fromJson(needs.initialize-matrix.outputs.matrix) }}
#
#    steps:
#      - name: Ballerina Build
#        uses: ballerina-platform/ballerina-action@master
#        with:
#          args:
#            build
