name: Build BBEs

on:
  workflow_dispatch:

jobs:
  initialize-matrix:
    name: Initialize Strategy Matrix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Strategy Matrix
        id: set-matrix
        run: |
          BBE_DATA_FILE="examples/index.json"
          bbes="["
          for index in $(jq '. | keys | .[]' $BBE_DATA_FILE); do samples=$(jq -r ".[$index].samples" $BBE_DATA_FILE) && for bbe_url in $(jq -r ".[].url" <<< "$samples"); do bbes="${bbes}${bbe_url}, "; done; done
          bbes="${bbes[1,-2]}]"
          echo ${bbes}
          echo "::set-output name=matrix::${bbes}"

    outputs:
      matrix: "${{ steps.set-matrix.outputs.matrix }}"

  build-bbe:
    needs: initialize-matrix
    name: Build BBE
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bbe: ${{fromJson(needs.initialize-matrix.outputs.matrix)}}

    steps:
      - name: Echo BBE
        run: echo ${{ matrix.bbe }}
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@master
        with:
          args:
            build

