name: CentOS Install Git

on:
  workflow_dispatch:

jobs:
  install-git:
    name: Install Git
    runs-on: ubuntu-latest
    container: centos:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install Git
        run: |
          yum install sudo -y
          sudo dnf install git -y
      - name: Download Ballerina Distribution
        run: git clone https://github.com/ballerina-platform/ballerina-distribution.git
   
