name: Create Tag

on:
  workflow_dispatch:

jobs:
  create_tag:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Create Tag
        run: |
          git tag -a v0.1.0 -m "Release v0.1.0"
          git push origin v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
