name: Custom Ballerina Action

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'ballerina version'
        required: true
        default: 'nightly'

jobs:
  build-project:
    name: Build Ballerina Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  #    - name: Set up JDK 11
  #      uses: actions/setup-java@v2
  #      with:
  #        distribution: 'temurin'
  #        java-version: '11'

      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args: init
        env:
          WORKING_DIR: examples/alternate-wait

      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args: build
        env:
          WORKING_DIR: examples/alternate-wait
