name: Delete Packages (Lang)

on:
  workflow_dispatch:

jobs:
  delete-packages:
    name: Delete Packages in Lang
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete packages
        run: |
          package_list=$(jq -r '.[] | .package' published-packages.json)
          for package in $package_list; \
          do echo “Package Name: $package"; \
          done


