name: Full Build Pipeline (patch branch)

on:
  workflow_dispatch:
    inputs:
      ballerina_lang_branch:
        description: 'Ballerina-lang branch'
        required: true
        default: 'master'
      enable_tests:
        type: choice
        description: 'Enable Tests'
        deprecationMessage: 'true or false'
        required: true
        options:
          - 'true'
          - 'false'
        default: 'true'

jobs:
  build-lang:
    name: Build Ballerina Lang
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Module Data
        run: |
          wget https://raw.githubusercontent.com/ballerina-platform/ballerina-release/master/dependabot/resources/extensions.json

      - name: Create Strategy Matrix
        id: set-matrix
        run: |
          MODULE_DATA_FILE="extensions.json"

          modules="["
          for moduleName in $(jq '.standard_library| .[] | .name' $MODULE_DATA_FILE); \
          do modules="${modules}${moduleName}, "; \
          done
          modules="${modules/%??/}]"
          echo "::set-output name=modules::${modules}"

      - name: Clone Ballerina Lang Repository
        run: git clone https://github.com/${{ github.repository_owner }}/ballerina-lang.git

      - name: Checkout To Lang Branch
        run: |
          cd ballerina-lang
          git checkout ${{ github.event.inputs.ballerina_lang_branch }}

      - name: Get Lang Version
        id: lang-version
        run: |
          VERSION=$((grep -w "version" | cut -d= -f2) < ballerina-lang/gradle.properties)
          echo "::set-output name=version::$VERSION"

      - name: Build ballerina-lang
        run: |
          cd ballerina-lang
          ./gradlew clean build -x check publishToMavenLocal --stacktrace --scan

      - name: Archive Lang Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ballerina Lang Artifacts
          path: ~/.m2/

    outputs:
      lang_version: ${{ steps.lang-version.outputs.version }}
      modules: ${{ steps.set-matrix.outputs.modules }}

  build-module:
    needs: build-lang
    name: Build Module
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ${{fromJson(needs.build-lang.outputs.modules)}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Ballerina Lang Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Ballerina Lang Artifacts
          path: ~/.m2/

      - name: Clone Module
        run: git clone https://github.com/ballerina-platform/${{ matrix.module }}.git

      - name: Update Lang Version in Module
        run: |
          perl -pi -e "s/^\s*ballerinaLangVersion=.*/ballerinaLangVersion=${{ needs.build-lang.outputs.lang_version }}/" ${{ matrix.module }}/gradle.properties

      - name: Build Module
        run: |
          cd ${{ matrix.module }}
          testsEnabled=" -x test"
          if [ "${{ github.event.inputs.enable_tests }}" == "true" ]; then testsEnabled="" && echo "Tests are Enabled"; else echo "Tests are Disabled"; fi
          echo "./gradlew clean build${testsEnabled} --scan --stacktrace"
          ./gradlew clean build${testsEnabled} --stacktrace --scan
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}


#          devCentralToken: ${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }}
