name: Get Distribution Version

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *'   # 00:00 in LK time (GMT+5:30)

jobs:
  build-pipeline:
    name: Build Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 480
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Clone ballerina-distribution
        run: |
          git clone https://github.com/ballerina-platform/ballerina-distribution.git
#      - name: Build ballerina-distribution
#        working-directory: ballerina-distribution
#        run: ./gradlew clean build -x check -x test --stacktrace --scan
      - name: Get project version
        id: project-version
        run: |
          SHORT_VERSION=$((grep -w "version" | cut -d= -f2 | cut -d- -f1) < ballerina-distribution/gradle.properties)
          DIST_VERSION=$((grep -w "version" | cut -d= -f2) < ballerina-distribution/gradle.properties)
          CODE_NAME=$((grep -w 'codeName' | cut -d= -f2) < ballerina-distribution/gradle.properties)
          RELEASE_VERSION=$DIST_VERSION-$CODE_NAME
          echo "::set-output name=version::$RELEASE_VERSION"
          echo "::set-output name=sversion::$SHORT_VERSION"
          echo "::set-output name=codename::$CODE_NAME"
      - name: Echo version
        run: |
          echo ${{ steps.project-version.outputs.version }}
          echo ${{ steps.project-version.outputs.sversion }}
          echo ${{ steps.project-version.outputs.codename }}

      - name: Echo version
        run: |
          TEST="  test   "
          echo "Test: $TEST"
          echo "Test: ${TEST##*( )}"
