name: Install NodeJs

on:
  workflow_dispatch:

jobs:
  job1:
    name: Install NodeJS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Check version
        run: |
          node -v
          npm -v
