name: Daily Full Build Pipeline (New)

on:
  workflow_dispatch:
    inputs:
      lang_branch:
        description: 'ballerina-lang branch'
        required: true
        default: 'master'
      lang_version:
        description: 'ballerina-lang version [OPTIONAL] (This will use the version instead of a branch)'
        required: false
      patch_level:
        type: choice
        description: 'Patch Level (e.g.; 2201.4.x, 2201.3.x, master)'
        required: true
        options:
          - 'master'
          - '2201.4.x'
          - '2201.3.x'
        default: 'master'
      downstream_branch:
        description: 'downstream repo branch [OPTIONAL]'
        required: false
      skip_tests:
        type: boolean
        description: 'Skip tests'
        deprecationMessage: 'true or false'
        required: true
      update_stdlib_dependencies:
        type: boolean
        description: 'Update stdlib dependencies'
        deprecationMessage: 'true or false'
        required: true

jobs:
  build-pipeline:
    name: Build Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 10.22.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python Packages
        run: |
          pip install requests
          pip install httplib2
          pip install colorama
          pip install configobj
          pip install requests

      - name: Set command
        id: set-command
        shell: bash
        run: |
          FILE_PATH="./fbp"
          commands=($FILE_PATH)

          if (${{github.event.inputs.lang_version != ''}})
          then
            commands+=("--lang-version" "${{ github.event.inputs.lang_version }}")
          else
            commands+=("--lang-branch" "${{ github.event.inputs.lang_branch }}")
          fi

          if (${{github.event.inputs.patch_level != 'master'}})
          then
            commands+=("--patch-level" "${{ github.event.inputs.patch_level}}")
          fi

          if (${{ github.event.inputs.downstream_branch != ''}})
          then
            commands+=("--downstream-branch" "${{ github.event.inputs.downstream_branch}}")
          fi

          if (${{github.event.inputs.skip_tests}})
          then
            commands+=("--skip-tests")
          fi

          if (${{ github.event.inputs.update_stdlib_dependencies}})
          then
            commands+=("--update-stdlib-dependencies")
          fi

          command_string=""
          for value in "${commands[@]}"
          do
            command_string+=" $value"
          done

          echo $command_string
          echo "::set-output name=command::$command_string"

      - name: Build Modules
        run: |
          python -u scripts/new_full_build_pipeline.py ${{ steps.set-command.outputs.command }}
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          devCentralToken: ${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }}
