name: Daily Full Build Pipeline (New)

on:
  workflow_dispatch:
    inputs:
      lang_branch:
        description: 'ballerina-lang branch'
        required: true
        default: 'master'
      lang_version:
        description: 'ballerina-lang version [OPTIONAL] (This will use the version instead of a branch)'
        required: false
      enable_tests:
        type: choice
        description: 'Enable tests'
        deprecationMessage: 'true or false'
        required: true
        options:
          - 'true'
          - 'false'
        default: 'true'
      patch_level:
        type: choice
        description: 'Patch Level (e.g.; 2201.4.x, 2201.3.x, master)'
        required: true
        options:
          - 'master'
          - '2201.4.x'
          - '2201.3.x'
        default: 'master'
      downstream_branch:
        description: 'ballerina-lang branch'
        required: false
        default: 'master'
      update_stdlib_dependencies:
        type: choice
        description: 'Update stdlib dependencies'
        deprecationMessage: 'true or false'
        required: true
        options:
          - 'true'
          - 'false'
        default: 'true'

jobs:
  build-pipeline:
    name: Build Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 10.22.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python Packages
        run: |
          pip install requests
          pip install httplib2
          pip install colorama
          pip install configobj
          pip install requests

      - name: Build Modules
        shell: bash
        run: |
          commands=("./fbp")
          if [${{ github.event.inputs.lang_version }} != '']
          then
            commands+=(${{ github.event.inputs.lang_version }});
          else
            commands+=(${{ github.event.inputs.lang_branch }});
          fi

          for value in "${commands[@]}"
          do
            echo $value
          done

#          python -u scripts/new_full_build_pipeline.py ./fbp --skip-tests --update-stdlib-dependencies
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          devCentralToken: ${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }}
