name: Repository Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      branch_enabled:
        description: 'Branch enabled'
        type: choice
        required: true
        options:
          - 'true'
          - 'false'
        default: 'true'

jobs:
  trigger-repo-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Trigger workflow (Branch Enabled)
        if: ${{ github.event.inputs.branch_enabled }} == 'true'
        run: |
          curl -X POST \
          'https://api.github.com/repos/NipunaMadhushan/ballerina-examples/dispatches' \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
          --data "{
            \"event_type\": \"trigger-repo-dispatch\",
            \"client_payload\": {
              \"repoName\": \"ballerina-distribution\"
              \"branch\": \"2201.2.x\"
            }
          }"

      - name: Trigger workflow (Branch Disabled)
        if: ${{ github.event.inputs.branch_enabled }} == 'false'
        run: |
          curl -X POST \
          'https://api.github.com/repos/NipunaMadhushan/ballerina-examples/dispatches' \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
          --data "{
            \"event_type\": \"trigger-repo-dispatch\",
            \"client_payload\": {
              \"repoName\": \"ballerina-distribution\"
            }
          }"