name: Repository Dispatch

on:
  repository_dispatch:
    types: [trigger-repo-dispatch]

jobs:
  repo-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Echo payload
        run: |
          echo "Repo Name: ${{ github.event.client_payload.repoName }}"
          echo "Branch: ${{ github.event.client_payload.branch }}"

      - name: Branch Name
        if: ${{ github.event.client_payload.branch }}
        run: |
          echo "Branch: ${{ github.event.client_payload.branch }}"

      - name: Check Python Script
        run: |
          python scripts/handle_inputs.py ${{ github.event.client_payload.repoName }} ${{ github.event.client_payload.branch }}