name: Repository Dispatch

on:
  repository_dispatch:
    types: [trigger-repo-dispatch]

jobs:
  send-chat-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Echo payload
        run: |
          echo "Repo Name: ${{ github.event.client_payload.repoName }}"
          echo "Branch: ${{ github.event.client_payload.branch }}"
