name: Set Up Ballerina

on:
  workflow_dispatch:
    inputs:
      ballerin_version: 
        description: 'Ballerina version'
        required: true
        default: '2201.8.3'

env:
  BALLERINA_DISTRIBUTION_VERSION: 2201.8.3    # Update this with the latest Ballerina version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17.0.7
      - name: Set up Ballerina
        if: github.event_name == 'workflow_dispatch'
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: ${{ github.event.inputs.ballerin_version }}
      - name: Check Ballerina Version
        run: bal -v
