name: Pass Artifacts Between Jobs

on:
  workflow_dispatch:
    inputs:
      ballerina_lang_branch:
        description: 'Ballerina-lang branch'
        required: true
        default: '2201.0.x'
      enable_tests:
        type: choice
        description: 'Enable Tests'
        deprecationMessage: 'true or false'
        required: true
        options:
          - 'true'
          - 'false'
        default: 'false'

jobs:
  initialize-matrix:
    name: Build Ballerina Lang
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Ballerina Lang Repository
        run: git clone https://github.com/${{ github.repository_owner }}/ballerina-lang.git

      - name: Checkout To Lang Branch
        run: |
          cd ballerina-lang
          git checkout ${{ github.event.inputs.ballerina_lang_branch }}

      - name: Get Lang Version
        id: lang-version
        run: |
          VERSION=$((grep -w "version" | cut -d= -f2) < ballerina-lang/gradle.properties)
          echo "::set-output name=version::$VERSION"

      - name: Build ballerina-lang
        run: |
          cd ballerina-lang
          ./gradlew clean build -x check publishToMavenLocal --stacktrace --scan

      - name: Check .m2 Dir
        run: |
          ls -a
          cd ~/.m2
          ls -a

      - name: Archive Lang Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ballerina Lang Artifacts
          path: ~/.m2/

    outputs:
      lang_version: ${{ steps.lang-version.outputs.version }}

  build-module:
    needs: initialize-matrix
    name: Build Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Ballerina Lang Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Ballerina Lang Artifacts
          path: ~/

      - name: Clone Module
        run: git clone https://github.com/ballerina-platform/module-ballerina-io.git

      - name: Update Lang Version in Module
        run: |
          perl -pi -e "s/^\s*ballerinaLangVersion=.*/ballerinaLangVersion=${{ needs.initialize-matrix.outputs.lang_version }}/" module-ballerina-io/gradle.properties

      - name: Build Module
        run: |
          cd module-ballerina-io
          testsEnabled=" -x test"
          if [ "${{ github.event.inputs.enable_tests }}" == "true" ]; then testsEnabled="" && echo "Tests are Enabled"; else echo "Tests are Disabled"; fi
          echo "./gradlew clean build${testsEnabled} --scan --stacktrace"
          ./gradlew clean build${testsEnabled} --stacktrace --scan
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
#          devCentralToken: ${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }}
