name: Test File Read

on:
  workflow_dispatch:

jobs:
  read_file:
    name: Read File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read File
        run:
          FILE="failed-modules.txt"

          while read line; do
            echo $line;
          done < ${FILE}
        shell: bash
        
      - name: For Loop
        run:
          for i in 1 2 3 4 5; 
          do 
            echo "Hello"
            echo "World"
            echo "My Name is"
            echo "Nipuna Madhushan"
          done

