name: Windows Installer Build
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Ballerina release version'
        required: true
        default: '2201.10.2'
      short_version:
        description: 'Ballerina short version'
        required: true
        default: '2201.10.2'

jobs:
  windows-installer-build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Move to shorter path
        run: |
          mkdir D:\a\short-path
          move D:\a\ballerina-examples\ballerina-examples\repo D:\a\short-path

      - name: Test Dir
        working-directory: D:\a\short-path
        run: |
          cd repo
          ls
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Install GUID Generator
        run: dotnet tool install -g dotnet-guid --version 0.5.2
      # - name: Set up Wix Tool Kit
      #   run: $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
      #   shell: cmd
      # - name: Set path for candle and light
      #   run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
      #   shell: bash
      - name: Add WiX toolkit to PATH
        shell: bash
        run: echo "${WIX}bin" >> $GITHUB_PATH
      # - name: Install Wget
      #   run: choco install wget --no-progress
      # - name: Download Windows Intaller Zip
      #   run: |
      #     wget https://github.com/ballerina-platform/ballerina-distribution/releases/download/v${{ github.event.inputs.release_version }}/ballerina-${{ github.event.inputs.short_version }}-swan-lake-windows.zip
      - name: Download Windows Intaller Zip
        run: |
          echo default login NipunaMadhushan password ${{ secrets.BALLERINA_BOT_TOKEN }} >> _netrc
          curl --netrc-file _netrc -L -o ballerina-${{ github.event.inputs.short_version }}-swan-lake-windows.zip https://github.com/ballerina-platform/ballerina-distribution/releases/download/v${{ github.event.inputs.release_version }}/ballerina-${{ github.event.inputs.short_version }}-swan-lake-windows.zip
      - name: Test Dir
        run: |
          pwd
      - name: Check Files
        run: dir/b
        shell: cmd
      - name: Archive Ballerina Windows Zip
        uses: actions/upload-artifact@v4
        with:
          name: Ballerina Windows Zip
          path: ballerina-${{ github.event.inputs.short_version }}-swan-lake-windows.zip
      - name: Create windows-msi
        id: run_installers_msi
        run: |
          move installers\windows .\
          ren windows w
          cd w
          .\build-ballerina-windows-x64.bat --version ${{ github.event.inputs.short_version }}-swan-lake --path .\..\
          echo "Created windows-msi successfully"
      - name: Generate Hashes
        run: |
          openssl dgst -sha256 -out ballerina-${{ github.event.inputs.short_version }}-swan-lake-windows-x64.msi.sha256 w\target\msi\ballerina-*-windows-x64.msi
      - name: Archive Windows msi Hashes
        uses: actions/upload-artifact@v4
        with:
          name: Windows msi Hashes
          path: ballerina-${{ github.event.inputs.short_version }}-swan-lake-windows-x64.msi.sha256
      - name: Archive Windows msi
        uses: actions/upload-artifact@v4
        with:
          name: Windows Installer msi
          path: w\target\msi\ballerina-*-windows-x64.msi

