name: Test If Statement

on:
  workflow_dispatch:
    inputs:
      patch_level:
        type: choice
        description: 'Patch Level (e.g.; 2201.4.x, 2201.3.x, master)'
        required: true
        options:
          - 'master'
          - '2201.8.x'
          - '2201.7.x'
          - '2201.6.x'
          - '2201.5.x'
          - '2201.4.x'
          - '2201.3.x'
        default: 'master'
        
env:
  DISTRIBUTION_BUILD_LEVEL: 11

jobs:
  build-lang:
    name: Build ballerina-lang
    runs-on: ubuntu-latest
    timeout-minutes: 150
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Java Verison
        id: java-version
        run: |
          JAVA_VERSION=""
          patch_level=${{ github.event.inputs.patch_level }}
          if [[ "$patch_level" == "master" ]]; then
            JAVA_VERSION="17";
          else
            update_version="$(cut -d'.' -f2 <<<"$patch_level")" &&
            update_version=$((update_version)) &&
            if [[ $update_version -ge 8 ]]; then JAVA_VERSION="17"; else JAVA_VERSION="11"; fi;
          fi;
          
          echo "::set-output name=version::$JAVA_VERSION"
      - name: Set up JDK 17.0.7
        if: ${{ steps.java-version.outputs.version == '17' }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.0.7'
      - name: Set up JDK 11
        if: ${{ steps.java-version.outputs.version == '11' }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
